version: '3'

services:
  k3s:
    # https://k3s.io
    image: rancher/k3s:v0.4.0
    command: server --node-name=k3s
    privileged: true
    ports:
      - "6443:6443"
      - "30080:30080"
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/config
      - K3S_KUBECONFIG_MODE=666
    volumes:
      # This will allow us to connect to the cluster.
      - ./.kube:/output
      # Inject our code in so we can run a test application.
      - .:/code
      # Automatically provision.
      - ./local/manifests/app.yaml:/var/lib/rancher/k3s/server/manifests/app.yaml
      - ./local/manifests/custom-metrics.yaml:/var/lib/rancher/k3s/server/manifests/custom-metrics.yaml
