# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/kubernetes-incubator/custom-metrics-apiserver"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/prometheus/common"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/tomasen/fcgi_client"

[[constraint]]
  branch = "release-1.14"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "release-11.0"
  name = "k8s.io/client-go"

[[constraint]]
  branch = "release-1.14"
  name = "k8s.io/component-base"

[[constraint]]
  branch = "release-1.14"
  name = "k8s.io/metrics"

[prune]
  go-tests = true
  unused-packages = true
